spring:
  application:
    name: eureka-server
  profiles: dis2
server:
  port: 8761
eureka:
  instance:
    hostname: dis2
    ipAddress: 10.211.55.9
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://10.211.55.8:8761/eureka/, http://10.211.55.10:8761/eureka/
    fetch-registry: true
    register-with-eureka: true