spring:
  application:
    name: eureka-server
  profiles: dis2
server:
  port: 8761
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://10.22.55.8:8761/eureka/, http://10.22.55.10:8761/eureka/
    fetch-registry: true
    register-with-eureka: true