spring:
  application:
    name: eureka-server
  profiles: discovery2
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://discovery1:8761/eureka/, http://discovery1:8763/eureka/
    fetch-registry: true
    register-with-eureka: true