spring:
  application:
    name: eureka-server
  profiles: dis2
server:
  port: 8761
eureka:
  instance:
    appname: eureka-server
    hostname: dis2
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://dis1:8761/eureka/,http://dis3:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000