spring:
  application:
    name: eureka-server
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://discovery2:8762/eureka/, http://discovery3:8763/eureka/
    fetch-registry: true
    register-with-eureka: true