spring:
  application:
    name: eureka-server
  profiles: discovery3
server:
  port: 8763
eureka:
  instance:
    hostname: discovery3
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://discovery2:8762/eureka/, http://discovery1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true