spring:
  application:
    name: eureka-server
  profiles: dis2
server:
  port: 8762
eureka:
  instance:
    hostname: dis2
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://dis1:8761/eureka/, http://dis3:8761/eureka/
    fetch-registry: true
    register-with-eureka: true