spring:
  application:
    name: eureka-server
  profiles: dis3
server:
  port: 8763
eureka:
  instance:
    hostname: dis3
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://dis2:8761/eureka/, http://dis1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true