spring:
  application:
    name: eureka-server
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://discovery1:8761/eureka/, http://discovery3:8763/eureka/
    fetch-registry: true
    register-with-eureka: true