spring:
  application:
    name: eureka-server
  profiles: discovery3
server:
  port: 3763
eureka:
  instance:
    hostname: discovery3
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://discovery2:3762/eureka/, http://discovery1:3761/eureka/
    fetch-registry: true
    register-with-eureka: true