spring:
  application:
    name: eureka-server
  profiles: dis
server:
  port: 8761
eureka:
  instance:
    hostname: dis1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      default-zone: http://dis2:8761/eureka/, http://dis3:8761/eureka/
    fetch-registry: true
    register-with-eureka: true