spring:
  application:
    name: eureka-server
  profiles: discovery1
server:
  port: 3761
eureka:
  instance:
    hostname: discovery1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://discovery2:3762/eureka/, http://discovery3:3763/eureka/
    fetch-registry: true
    register-with-eureka: true